version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./uploads:/app/uploads
      - ./chroma_store:/app/chroma_store
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URL=${NEO4J_URL}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - REDIS_URL=${REDIS_URL}
      - CHROMA_PERSIST_DIR=${CHROMA_PERSIST_DIR}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: langgraph_redis
    ports:
      - "6379:6379"
    restart: always

  neo4j:
    image: neo4j:5.19
    container_name: langgraph_neo4j
    environment:
      NEO4J_AUTH: "neo4j/12345678"
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j_data:/data
    restart: always