version: '3.9'
services:
  fastapi:
    build: .
    container_name: langgraph_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - neo4j
    environment:
      - REDIS_URL=redis://redis:6379/0
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=123456
    volumes:
      - ./chroma_store:/app/chroma_store
      - ./uploads:/app/uploads
    restart: always

  redis:
    image: redis:7
    container_name: langgraph_redis
    ports:
      - "6379:6379"
    restart: always

  neo4j:
    image: neo4j:5.19
    container_name: langgraph_neo4j
    environment:
      NEO4J_AUTH: "neo4j/12345678"
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j_data:/data
    restart: always

